Using OSRM for routing over pgrouting
trifectalabs/roadquality pull request #28
Opened 2017-08-08 19:59 UTC by wittjosiah

2017-08-09 03:20 UTC, kiambogo requested changes
I also would like the profile stuff to be under resources/orsm/profiles/... personally

2017-08-09 03:20 UTC, kiambogo commented on api/conf/application.conf
> +osrm.nearest.uri = ${OSRM_NEAREST_URI}
Are these different enough to merit two separate lines? Why not have osrm.uri and then just use constants for the routing path vs the nearest path? or are the two very different?

2017-08-09 03:20 UTC, kiambogo commented on api/app/services/RoutingService.scala
> +    ws.url(osrmUrl).get().map { res =>
what happens if this fails? we need to handle the case that OSRM is down - i.e., return a 503 and handle gracefully on the client

2017-08-09 03:20 UTC, kiambogo commented on api/app/services/RoutingService.scala
> +    ws.url(osrmUrl).get().map { res =>
you can pattern match on the status

2017-08-09 16:41 UTC, wittjosiah commented
addressed your comments @kiambogo

2017-08-10 01:57 UTC, kiambogo commented on api/app/services/RoutingService.scala
> +      Point(
This isn't elm - lng should be on the same line as Point. ;)

2017-08-10 01:57 UTC, kiambogo approved these changes

2017-08-10 23:48 UTC, merged